import { HeadingDef1, HeadingDef2, HeadingDef3 } from "@/app/Components/heading/Heading"


import "./about.css"
import Image from "next/image"
import BottumColorized from "@/app/Components/bottumColorized/bottumColorized"
import Link from "next/link"

export const metadata = {
    title: "درباره من",
    description: 'Generated by create next app',
}



export default async function About() {
 


    return (
        <main>
            <HeadingDef1 txt="کیستم؟" />
            <HeadingDef2 txt="محمد حسن مسیب نژاد" />
            <HeadingDef3 txt="لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ
 و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه
روزنامه و مجله در ستون و سطرآنچنان که لازم است، و"/>


            <div className="radif">
                <div className="soton leaiefiauh">قم</div>
                <div className="soton rightkabasbh">محل تولد</div>

            </div>
            <div className="radif">
                <div className="soton leaiefiauh">لاهیجان</div>
                <div className="soton rightkabasbh">محل زندگی</div>

            </div>
            <div className="radif">
                <div className="soton leaiefiauh sasdaef">00998</div>
                <div className="soton rightkabasbh">شماره همراه</div>

            </div>
            <div className="radif">
                <div className="soton leaiefiauh sasdaef">18سال</div>
                <div className="soton rightkabasbh">تاریخ تولد</div>

            </div>


            <div className="radif">
                <div className="soton leaiefiauh sizethaasduhiu">mohammadmosayyebnezhad@gmail.com</div>
                <div className="soton rightkabasbh ">ایمیل</div>

            </div>
            <HeadingDef1 className="asoane" txt="چه کردم؟" />

            <div className="radif">
                <div className="soton ">
                    <Image className="myimageformeeaouefae" width={186} height={607} src={"https://image.mosayyebnezhad.ir/meb.webp"} style={{ transform: "scaleX(-1)" }} alt="" />

                </div>
                <div className="naoifhioaefui3qrh80 ">
                    <HeadingDef3 txt="لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در " />
                    <Link href={"/Pages/Portfolios"}>
                        <BottumColorized txt="رفتن به صفحه نمونه کارها" />
                    </Link>
                </div>

            </div>

        </main>
    )

}