
import Navbar from './Components/Navbar/Navbarcomponent'
import "./globals.css"
export const metadata = {
  title: {
    template: '%s | وبسایت شخصی محمد حسن مسیب نژاد ، طراحی وبسایت و گرافیست',
    default: 'وبسایت شخصی محمد حسن مسیب نژاد ، طراحی وبسایت و گرافیست', // a default is required when creating a template
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  var items = [
    'درباره من',
    'توانایی هایم',
    'سرویس هایم',
    'نمونه کار هایم',
    'مدارک من'
  ]

  return (

    <html lang="en">

      <body>
       
        <link rel="icon" href="./logo.svg" />
        <Navbar />

        {children}


      </body>
    </html>
  )
}
