import { HeadingDef1, HeadingDef2, HeadingDef3 } from "./Components/heading/Heading";
import Hireme from "./Components/Hireme/Hireme";


import { Dribbble, Github, Instagram, Pintrest, Twitter } from "./Components/Svglogos/svglogos";
import './globals.css'
import './Homepage.css'

export const metadata = {
  title: "صفحه اصلی",
  description: 'Generated by create next app',
}
export default async function Home() {

  return (
    <main>
      <HeadingDef1 txt="محمد حسن مسیب نژاد" />
      <HeadingDef2 txt="طراح وبسایت و گرافیست" />
      <HeadingDef3 txt="Full Stack developer in Back-Side By .Net and in Front-Side By Next.js And React.js , I enjoy the Path Follow me" />


      <div className="logoslist">
        <Dribbble width="22" />
        <Instagram width="22" />
        <Github width="24" />
        <Pintrest width="19" />
        <Twitter width="26" />
        {/* < width="30" /> */}

      </div>

      <Hireme />
    </main>
  )
}
