import { Button, Card, CardActions, CardContent, CardMedia, Container, Typography } from "@mui/material"
import "./certificate.css"
import Image from "next/image"
import Link from "next/link"
async function getme() {
    const res = await fetch(
        "https://64b17d54062767bc4826489f.mockapi.io/api/v1/users"
        , { cache: "no-store" })
    await new Promise((resolve) => setTimeout(resolve, 2000))
    return res.json()


}
export const metadata = {
    title: "مدارک من",
    description: 'Generated by create next app',
}


export default async function About() {
 var game = getme();
    return (

        <main className="eaxhafsfi">
            <Card className="aouscikabfef" sx={{ maxWidth: 345 }}>
                <Image src={"https://image.mosayyebnezhad.ir/Certificate/SignalR-certificate.jpg"} width={345} height={258} />

                <CardContent>
                    <Typography gutterBottom variant="h5" component="div" >
                        Signal R
                    </Typography>
                    <Typography variant="body2" >

                    </Typography>
                </CardContent>
                <CardActions>

                    <Link href={"https://image.mosayyebnezhad.ir/SignalR-certificate.pdf"} target="_blank">
                        <Button size="small">دانلود</Button>
                    </Link>

                </CardActions>
            </Card>
            <Card className="aouscikabfef" sx={{ maxWidth: 345 }}>
                <Image src={"https://image.mosayyebnezhad.ir/Certificate/HTM%2CCSS-certificate.jpg"} width={345} height={258} />

                <CardContent>
                    <Typography gutterBottom variant="h5" component="div" >
                        HTML & Css
                    </Typography>
                    <Typography variant="body2" >

                    </Typography>
                </CardContent>
                <CardActions>

                    <Link href={"https://image.mosayyebnezhad.ir/HTM%2CCSS-certificate.pdf"} target="_blank">
                        <Button size="small">دانلود</Button>
                    </Link>

                </CardActions>
            </Card>
            <Card className="aouscikabfef" sx={{ maxWidth: 345 }}>
                <Image src={"https://image.mosayyebnezhad.ir/Certificate/C"} width={345} height={258} />

                <CardContent>
                    <Typography gutterBottom variant="h5" component="div" >
                        C#
                    </Typography>
                    <Typography variant="body2" >

                    </Typography>
                </CardContent>
                <CardActions>

                    <Link href={"https://image.mosayyebnezhad.ir/C"} target="_blank">
                        <Button size="small">دانلود</Button>
                    </Link>

                </CardActions>
            </Card>
            <Card className="aouscikabfef" sx={{ maxWidth: 345 }}>
                <Image src={"https://image.mosayyebnezhad.ir/Certificate/VueJs-certificate.jpg"} width={345} height={258} />

                <CardContent>
                    <Typography gutterBottom variant="h5" component="div" >
                       Vue js
                    </Typography>
                    <Typography variant="body2" >

                    </Typography>
                </CardContent>
                <CardActions>

                    <Link href={"https://image.mosayyebnezhad.ir/VueJs-certificate.pdf"} target="_blank">
                        <Button size="small">دانلود</Button>
                    </Link>

                </CardActions>
            </Card>
        </main>

    )
}