import { HeadingDef1, HeadingDef3 } from "@/app/Components/heading/Heading"
import "./services.css"
async function getme() {
    const res = await fetch(
        "https://64b17d54062767bc4826489f.mockapi.io/api/v1/MainDB"
        , { cache: "no-store" })
    await new Promise((resolve) => setTimeout(resolve, 2000))
    return res.json()


}
export const metadata = {
    title: "سرویس های من",
    description: 'Generated by create next app',
}

export default async function About() {
var game = getme()
    return (
        <main>
            <section className="secinservices">
                <div>
                <iframe src="https://my.spline.design/componentuicopy-9a1ca10affd19ecd1759d8440d92f5aa/" width={"100%"} height={"600px"}/>
                </div>
                <div>
                    <HeadingDef1 txt="طراحی سایت" />
                    <HeadingDef3 txt="لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در  و مجله " />

                </div>
            </section>
            <section className="secinservices">
                
                <div>
                    <HeadingDef1 txt="گرافیست" />
                    <HeadingDef3 txt="لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله " />

                </div>
                <div>
                <iframe src="https://my.spline.design/polaroidgocopy-622613c48b5d7bdcbe78779c09f629e9/" width={"100%"} height={"600px"}/>
               
                </div>
            </section>
        </main>
    )
}