
import { HeadingDef1, HeadingDef3 } from "@/app/Components/heading/Heading"
import "./services.css"
import LottieF from "@/app/Components/Lottie/Lottie"
import Link from "next/link"
import BottumColorized from "@/app/Components/bottumColorized/bottumColorized"
// async function getme() {
//     const res = await fetch(
//         "https://64b17d54062767bc4826489f.mockapi.io/api/v1/MainDB"
//         , { cache: "no-store" })
//     await new Promise((resolve) => setTimeout(resolve, 2000))
//     return res.json()
// }
export const metadata = {
    title: "سرویس های من",
    description: 'Generated by create next app',
}

export default async function About() {
    // var game = getme()
    return (
        <main>
            <section className="secinservices">
                <div className="a9efhw978fh65661651">
                    <LottieF src={"https://lottie.host/cc76090f-e4b7-4652-adb8-caecf0904c03/PHbvYdtWRr.json"} width={"auto"} height={"auto"} />


                </div>
                <div>
                    <HeadingDef1 txt="طراحی سایت" />
                    <HeadingDef3 txt="لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در  و مجله " />

                </div>
            </section>
            <section className="secinservices">

                <div>
                    <HeadingDef1 txt="گرافیست" />
                    <HeadingDef3 txt="لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله " />

                </div>
                <div>
                    <LottieF src={"https://lottie.host/3d9105af-409b-497f-91d0-52881b95105e/dZiZtanoGq.json"} width={"auto"} height={"auto"} />

                </div>
            </section>
           
            <div style={{ width: "100%", float: "left", display: "flex", alignItems: "center", justifyContent: "space-around", marginBottom: "120px",flexWrap:"wrap" }}>
                <div style={{ borderRadius: "5vw", width: "50%", overflow: "hidden" }}>
                    <LottieF src={"https://lottie.host/c790c043-e4c3-459c-82d5-ca6acd4882ae/kuAUKLkQox.json"} width={"100%"} height={"auto"} />
                </div>
                <Link href={"/Pages/Portfolios"} >
                    <BottumColorized txt="رفتن به صفحه نمونه کار ها" />
                </Link>
            </div>
        </main >
    )
}